spring.application.name=SpringAIP04
logging.pattern.console=%yellow(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %green(%logger{36}) %yellow(:%line) -%msg%n
server.port=8082

spring.ai.openai.api-key=${OPEN_API_KEY}

logging.level.org.springframework.ai.chat.client.advisor=DEBUG
