spring.application.name=ChatBot

gemini.api.key={API_KEY}
gemini.model=gemini-2.5-flash
logging.pattern.console=%yellow(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %green(%logger{36}) %yellow(:%line) -%msg%n
logging.level.root=INFO