spring.application.name=RAGP01



logging.level.org.springframework.ai.chat.client.advisor=DEBUG
logging.pattern.console=%yellow(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %green(%logger{36}) %yellow(:%line) -%msg%n

spring.ai.openai.api-key=${OPENAI_API_KEY:${OPEN_API_KEY:}}
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.chat.options.max-tokens=300
spring.ai.openai.chat.options.temperature=0.2


spring.ai.vectorstore.qdrant.host=localhost
spring.ai.vectorstore.qdrant.port=6334
spring.ai.vectorstore.qdrant.collection-name=rag_ai_p01
spring.ai.vectorstore.qdrant.initialize-schema=true
spring.ai.vectorstore.qdrant.use-tls=false

spring.docker.compose.stop.command=DOWN

tavily.api-key=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
tavily.result-limit=5