spring.application.name=GenAiP04


logging.pattern.console=%yellow(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %green(%logger{36}) %yellow(:%line) -%msg%n

spring.ai.openai.api-key=${OPEN_API_KEY}

logging.level.org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor=DEBUG


