spring.application.name=Order-service

server.port=8082
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

#Actuator
management.endpoints.web.exposure.include=*

logging.level.root=INFO

